// <auto-generated />
using System;
using CustomerService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250224045939_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Models.TBL_CUSTOMER", b =>
                {
                    b.Property<int>("CUSTOMERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CUSTOMERID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<string>("CUSTOMERCODE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DATETIMEUPDATED")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LASTUPDATEDBY")
                        .HasColumnType("int");

                    b.Property<string>("OCCUPATION")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CUSTOMERID");

                    b.ToTable("TBL_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.TBL_CUSTOMER_ORDER", b =>
                {
                    b.Property<int>("CUSTOMERORDERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CUSTOMERORDERID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CUSTOMERID")
                        .HasColumnType("int");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DELIVERYADDRESS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ORDERDATE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ORDERRECEIVEDBY")
                        .HasColumnType("int");

                    b.HasKey("CUSTOMERORDERID");

                    b.HasIndex("CUSTOMERID");

                    b.ToTable("TBL_CUSTOMER_ORDER", (string)null);
                });

            modelBuilder.Entity("CustomerService.Models.TBL_CUSTOMER_ORDER", b =>
                {
                    b.HasOne("CustomerService.Models.TBL_CUSTOMER", "CUSTOMER")
                        .WithMany("ORDERS")
                        .HasForeignKey("CUSTOMERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CUSTOMER");
                });

            modelBuilder.Entity("CustomerService.Models.TBL_CUSTOMER", b =>
                {
                    b.Navigation("ORDERS");
                });
#pragma warning restore 612, 618
        }
    }
}
