apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip-svc
spec:
  type: ExternalName
  externalName: host.docker.internal  # Replace with your local machine IP on Linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqllocaldb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
        - name: customerservice
          image: adeakinwe/customerservice:net8.0
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mysql-clusterip-svc;Port=3306;Database=CUSTOMERSERVICEDB;User=root;Password=$(MYSQL_ROOT_PASSWORD);"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD